# Generated by Django 4.1.5 on 2023-01-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digial',
            new_name='digital',
        ),
    ]
